### ISSUE TITLE
Dragging range slider with the middle does not generate change event

### ISSUE THREAD

**Issue by JosefJezek** [IftachSadeh/paper-range-slider#13]
![image](https://cloud.githubusercontent.com/assets/2110319/24414472/c7ccf996-13de-11e7-9368-8040c7cb85bc.png)
![image](https://cloud.githubusercontent.com/assets/2110319/24414547/fc543594-13de-11e7-8651-9febf38d8aab.png)

Please add `cursor: col-resize;` for dragging range slider. Check out this lib https://refreshless.com/nouislider/

**Comment by JosefJezek** [comment]
@IftachSadeh please

**Comment by IftachSadeh** [comment]
Check out v0.2.6

**Comment by JosefJezek** [comment]
@IftachSadeh `change` event is not generated... I am using `on-change="_onSliderChange"`

**Comment by IftachSadeh** [comment]
Can you please give a full example of what you're doing?

**Comment by JosefJezek** [comment]
@IftachSadeh Check out this video...

https://drive.google.com/file/d/0BxfDxwIOORSYdDYya0ZzZUktWWM/view

**Comment by tlg-tejas** [comment]
This is not working for me too, can we have a solution for this
