### ISSUE TITLE
Event `value-min-changed` is fired on initialization

### ISSUE THREAD

**Issue by dkalinin** [IftachSadeh/paper-range-slider#21]
When I declaratively attach a handler for `value-min-changed` event it is fired with initial value:
```html
<paper-range-slider
                    min="0"
                    max="100"
                    value-min="0"
                    value-max="100"
                    on-value-min-changed="_handleMinValueChange">
                    </paper-range-slider>
```
Live demo: https://codepen.io/dkalinin/pen/KQambB?editors=1001

If I attach a handler imperatively in `connectedCallback` then it is not fired.
Polymer version 2.3+
paper-range-slider v1.0.2

**Comment by IftachSadeh** [comment]
This should now be resolved. Check `CHANGELOG.md` for details.

**Comment by dkalinin** [comment]
@IftachSadeh Thanks, it's not firing the event in paper-range-slider v1.0.3:
https://codepen.io/dkalinin/pen/odxYXX?editors=1001
