### ISSUE TITLE
Not read property 'style'

### ISSUE THREAD

**Issue by vseba90** [IftachSadeh/paper-range-slider#5]
Hello! When i install your component, and try to use it, the console brings this error.

Uncaught TypeError: Cannot read property 'style' of null  // paper-range-slider.html:736 

You know about this?

Regards!

**Comment by IftachSadeh** [comment]
Hey,
`paper-range-slider` uses `paper-slider`.
Can you please tell me which versions of `Polymer` and of `paper-slider` you use? Also, which browser?

**Comment by IftachSadeh** [comment]
This problem should be resolved as of v0.2.0
