### ISSUE TITLE
Cannot read property 'offsetWidth' of null

### ISSUE THREAD

**Issue by juanpicuervo** [IftachSadeh/paper-range-slider#6]
Hi, im using the latest version of paper-range-slider (0.2.2) and paper-slider(1.0.11).

When i try to change range of any slider it gives me the following error:

paper-range-slider.html:663 Uncaught TypeError: Cannot read property 'offsetWidth' of null.

Also it gives me this error:
paper-range-slider.html:357 could not properly initialize the underlying paper-slider elements ...

**Comment by IftachSadeh** [comment]
I've updated the Master version with a possible fix.
Can you please check it out and let me know if the bug persists?
Thanks,

**Comment by juanpicuervo** [comment]
Hi, its still the same error

**Comment by IftachSadeh** [comment]
Which browser (&version) are you using?

**Comment by juanpicuervo** [comment]
Google chrome: Version 53.0.2785.143 (64-bit)

**Comment by IftachSadeh** [comment]
If you define the `paper-range-slider`, but do not try to programmatically change the range (or any other coded action), does the element work without errors?

**Comment by juanpicuervo** [comment]
No, im trying the following example:

`     <paper-range-slider pin value-diff-min="14" value-diff-max="28" value-max="40" max="60" min="-10"></paper-range-slider>`

Im not doing nothing programatically.

**Comment by juanpicuervo** [comment]
I will make a pull request with the fixes. maybe it helps.

**Comment by IftachSadeh** [comment]
Thanks for that.
Can you please check out the just-updated Master again?

**Comment by juanpicuervo** [comment]
Yes, now is working :)

**Comment by IftachSadeh** [comment]
Awesome.
Thanks again for helping to improve the element!
