### ISSUE TITLE
#sliderKnobInner is null

### ISSUE THREAD

**Issue by justweb1** [IftachSadeh/paper-range-slider#8]
#sliderKnobInner is null on the lines shown below. This happens on initialization of the component.

**Issue location:**
https://github.com/IftachSadeh/paper-range-slider/blob/09ab01882a1138e847f02cb5e346b10804d93284/paper-range-slider.html#L343-L366

**Stack Trace:**
![image](https://cloud.githubusercontent.com/assets/11264693/19621321/df9a0de4-9854-11e6-85fc-b1e44f921b75.png)

cc @balloob @turbokongen @IftachSadeh

**Comment by justweb1** [comment]
it looks like paper-slider renamed KnobInner. Can you edit your element so it doesn't reach into the paper-slider shadow dom?

**Comment by balloob** [comment]
It looks like paper-slider 1.0.12 has renamed `#sliderKnobInner` to be `.slider-knob-inner`.

I think that this is a bad behavior to begin with. `paper-range-slider` shouldn't try to change anything inside the ShadowDOM of another web component. Why not just set disabled = true ?

**Comment by IftachSadeh** [comment]
A temporary fix is given in v0.2.4.
